---
- name: add sudo group
  group:
    name: sudo
    state: present
  tags:
    - sudo

- name: add no password to sudo
  become: yes
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%sudo'
    line: '%sudo ALL=(ALL:ALL) NOPASSWD:ALL'
    validate: 'visudo -cf %s'
  tags:
    - sudo
...